adobecom/news

scripts/scripts.js

https://jira.corp.adobe.com/browse/MWPW-146710

MWPW-146710-enable analytics

---

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml
.github/workflows/run-lint.yaml

Jira: https://jira.corp.adobe.com/browse/MWPW-146720

MWPW-146720- Set gitHub workflow

---

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml
.github/workflows/run-lint.yaml
scripts/scripts.js

Following PR is getting synched
https://github.com/adobecom/news/pull/4

Stage to main sync

---

.kodiak/config.yaml

Jira: https://jira.corp.adobe.com/browse/MWPW-146867

MWPW-146867-Add Kodiak Config.yaml

---

helix-query.yaml
helix-sitemap.yaml

* Setup sitemap
Resolves: [MWPW-148128](https://jira.corp.adobe.com/browse/MWPW-148128)
**Test URLs:**
- Before: https://main--news--adobecom.hlx.live/?martech=off
- After: https://sitemap--news--adobecom.hlx.live/?martech=off

MWPW-148128 - Setup sitemap

---

scripts/scripts.js

Set up pdf embed api keys for stage and prod
https://jira.corp.adobe.com/browse/MWPW-146639

MWPW-146639-set pdf embed api key

---

.github/workflows/run-lint.yaml
package-lock.json
package.json
scripts/fallback.js
web-test-runner.config.js

Test URL:
Before: https://stage--news--adobecom.hlx.live/drafts/ruchika/document?martech=off
After: https://fallback--news--adobecom.hlx.live/drafts/ruchika/document?martech=off

Fix lint issues in fallback and test runner config files

---

helix-query.yaml

Jira:  https://jira.corp.adobe.com/browse/MWPW-158806

Sitemap update

---

scripts/scripts.js

https://jira.corp.adobe.com/browse/MWPW-159080

MWPW-159080-Add lana logging

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

Revert "news.adobe.com to hlx-5"

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

Revert "Revert "news.adobe.com to hlx-5""

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

Revert "Revert "Revert "news.adobe.com to hlx-5"""

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

Update news.adobe.com to hlx-5

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

Revert "Upgrade to hlx5"

---

tools/sidekick/config.json

* MWPW-146930 - Rollout tool plugin
Adding rollout plugin to sidekick config
Resolves: MWPW-146930
* Add Project Name
Adding Project Name for SideKick
* MWPW-146930 - Rollout tool plugin
Adding project as "news"

MWPW-146930 - Rollout tool plugin (#52)

---

scripts/utils.js
test/scripts/utils.test.js
tools/sidekick/config.json

https://jira.corp.adobe.com/browse/MWPW-166197

Upgrade to hlx5

---

scripts/scripts.js

https://jira.corp.adobe.com/browse/MWPW-169364
https://jira.corp.adobe.com/browse/MWPW-166376

Set up config for ROW and update pdf embed api key to support .aem urls

---

tools/sidekick/config.json

https://jira.corp.adobe.com/browse/MWPW-167958
Update sidekick to remove Localize and add bulk CaaS publisher link

MWPW-167958-Update sidekick to remove Localize and add bulk CaaS publisher link

---

helix-query.yaml
helix-sitemap.yaml

https://jira.corp.adobe.com/browse/MWPW-166377

MWPW-166377-Set up sitemap for ROW

---

helix-query.yaml
helix-sitemap.yaml

https://jira.corp.adobe.com/browse/MWPW-166377

MWPW-166377- Set up sitemap for ROW

---

helix-query.yaml
helix-sitemap.yaml

PR:
- https://github.com/adobecom/news/pull/61

[Release]Stage to Main Sync 3/26

---

scripts/scripts.js

https://language-site--news--adobecom.aem.page/?milolibs=stage
https://language-site--news--adobecom.aem.page/ko/?milolibs=stage
https://language-site--news--adobecom.aem.page/en/gb/?milolibs=stage

Language site

---

scripts/scripts.js

Jira: https://jira.corp.adobe.com/browse/MWPW-171547
Test URLs
- Before: https://stage--news--adobecom.aem.page/ja/
- After: https://ietf--news--adobecom.aem.page/ja/

[MWPW-171547] Fix ietf error

---

scripts/scripts.js

Resolves: [MWPW-171549](https://jira.corp.adobe.com/browse/MWPW-171549)
Test Pages:
- Before: https://stage--news--adobecom.aem.page/fr/
- After: https://stage-mapping--news--adobecom.aem.page/fr/
www.adobe.com urls will be converted to www.stage.adobe.com urls on aem.page and news.stage.adobe.com urls except the earning pdf.

[MWPW-171549] Update Stage Domain Mapping

---

scripts/scripts.js

Resolves: [MWPW-171549](https://jira.corp.adobe.com/browse/MWPW-171549)
Test Pages:
Before: https://stage--news--adobecom.aem.page/fr/
After: https://stage-mapping--news--adobecom.aem.page/fr/

[MWPW-171549] Update Stage Domain Mapping for news domain

---

scripts/scripts.js

Resolves: [MWPW-171549](https://jira.corp.adobe.com/browse/MWPW-171549)
Test Pages:
Before: https://stage--news--adobecom.aem.page/fr/
After: https://test-stage--news--adobecom.aem.page/fr/

[MWPW-171549]Update Stage Domain Mapping for news domain

---

robots.txt

Resolves: [MWPW-174992](https://jira.corp.adobe.com/browse/MWPW-174992)
Test Pages:
Before: https://stage--news--adobecom.aem.live/
After: https://row-robots--news--adobecom.aem.live/

[MWPW-174992] Add row sitemaps to robots.txt

---

helix-query.yaml

Resolves:
[MWPW-177125](https://jira.corp.adobe.com/browse/MWPW-177125)

Fix indentation

---

helix-query.yaml

- https://github.com/adobecom/news/pull/78

[Release]Stage to Main

---

akamai/sureroute-test-object.html

Resolves: https://jira.corp.adobe.com/browse/MWPW-177295
Creating sureroute-test-object.html file for akamai

[MWPW-177295]Creating sureroute-test-object.html file for akamai

---

akamai/sureroute-test-object.html

PR
- https://github.com/adobecom/news/pull/80

[Release] Stage to Main
